/**
 * 이벤트 코드 정의 파일.
 *
 * Copyright (c) 2002-2003 팀메이, All rights reserved.
 *
 * @author	파란~*
 * @date	$Date: 04-08-27 8:00p $
 * @version	$Revision: 36 $
 *
 * <HR>
 * $Log: /UInterface/Inc/W3DEventCode.h $
 * 
 * 36    04-08-27 8:00p Paran
 * 
 * 35    04-08-23 8:39p Paran
 * 
 * 2     03-05-20 9:35p Paran			계속 수정 중...
 * 
 * <HR>
 *
 * @file	W3DEventCode.h
 */


#ifndef __Wind3D_UInterface_EventCode_Header__
#define __Wind3D_UInterface_EventCode_Header__

#define UIEVENT		int

const UIEVENT	EVENT_BUTTON				= 201;
const UIEVENT	EVENT_EDITTEXTCLICK			= 202;
const UIEVENT	EVENT_PICTUREBOXCLICK		= 203;
const UIEVENT	EVENT_RETURNKEY				= 204;
const UIEVENT	EVENT_TABKEY				= 205;
const UIEVENT	EVENT_EDITTEXTNEW			= 206;			///< 에디트박스 입력 완료시.
const UIEVENT	EVENT_KEYDOWN				= 207;
const UIEVENT	EVENT_KEYUP					= 208;
const UIEVENT	EVENT_MOUSEBOTTON			= 209;
const UIEVENT	EVENT_SHOWDLG				= 210;
const UIEVENT	EVENT_SENDCHATTING			= 211;

const UIEVENT	EVENT_ITEM_INSERTINVENTORY	= 300;
const UIEVENT	EVENT_ITEM_HOLDING			= 301;
const UIEVENT	EVENT_ITEM_CHANGEHAND		= 302;
const UIEVENT	EVENT_ITEM_MOVE				= 303;
const UIEVENT	EVENT_ITEM_DROP				= 304;
const UIEVENT	EVENT_ITEM_INSERTEQUIP		= 305;
const UIEVENT	EVENT_ITEM_REMOVEQUIP		= 306;
const UIEVENT	EVENT_ITEM_TOMAP			= 307;
const UIEVENT	EVENT_SPELL_MOVE			= 308;
const UIEVENT	EVENT_CAST_ITEM				= 309;
const UIEVENT	EVENT_DBCLICK_ITEM			= 310;
const UIEVENT	EVENT_USEQUICKITEM			= 311;
const UIEVENT	EVENT_ITEM_AUTOPICKUP		= 312;
const UIEVENT	EVENT_ENCHANT				= 313;
const UIEVENT	EVENT_ENCHANT_CHANGE		= 314;
const UIEVENT	EVENT_ENCHANT_COLLECTION	= 315;
const UIEVENT	EVENT_ITEMROOK				= 316;
const UIEVENT	EVENT_LEVELROOK				= 317;
const UIEVENT	EVENT_USECASHITEM			= 318;
const UIEVENT	EVENT_GETBILLINGITEM		= 319;

const UIEVENT	EVENT_SETMAINSKILL			= 400;
const UIEVENT	EVENT_TALK_REQUEST			= 401;
const UIEVENT	EVENT_SMITH_REQUEST			= 402;
const UIEVENT	EVENT_SMITH_ADDITEM			= 403;
const UIEVENT	EVENT_SMITH_ENCHENT			= 404;
const UIEVENT	EVENT_SMITH_REMOVEITEM		= 405;
const UIEVENT	EVENT_CARDSUM				= 406;
const UIEVENT	EVENT_CARDUNDONPC			= 407;
const UIEVENT	EVENT_CARDUNDO				= 408;
const UIEVENT	EVENT_SERVER				= 409;
const UIEVENT	EVNET_SERVER_INTEGRATION_GARBAGE_REQUEST = 410;
const UIEVENT	EVENT_SERINT_GARBAGE_INIT	= 411;
const UIEVENT	EVENT_SERINT_GARBAGE_REMOVEITEM = 412;
const UIEVENT	EVENT_SERINT_INVEN_REQUIEST	= 413;
const UIEVENT	EVENT_SERINT_INVEN_INIT		= 414;
const UIEVENT	EVENT_SERINT_INVEN_REMOVEITEM = 415;

const UIEVENT	EVENT_ITEM_BUY				= 500;
const UIEVENT	EVENT_ITEM_SELL				= 501;
const UIEVENT	EVENT_SHOP_REQUEST			= 502;
const UIEVENT	EVENT_QUEST_REQUEST			= 503;
const UIEVENT	EVENT_QUEST_ACCEPT			= 504;
const UIEVENT	EVENT_STORAGE_REQUEST		= 505;
const UIEVENT	EVENT_STORAGE_ADDITEM		= 506;
const UIEVENT	EVENT_STORAGE_REMOVEITEM	= 507;
const UIEVENT	EVENT_STORAGE_SAVEGOLD		= 508;
const UIEVENT	EVENT_STORAGE_GETGOLD		= 509;
const UIEVENT	EVENT_GOTODEALMAP			= 510;

const UIEVENT	EVENT_DEAL_ADDITEM			= 550;
const UIEVENT	EVENT_DEAL_DELETEITEM		= 551;
const UIEVENT	EVENT_DEAL_ADDMONEY			= 552;
const UIEVENT	EVENT_DEAL_CHECKIN			= 553;
const UIEVENT	EVENT_DEAL_SUBMITOK			= 554;
const UIEVENT	EVENT_DEAL_CANCEL			= 555;
const UIEVENT	EVENT_DEAL_REQUEST			= 556;

const UIEVENT   EVENT_PARTY_CREATE			= 600;
const UIEVENT   EVENT_PARTY_DESTROY			= 601;
const UIEVENT   EVENT_PARTY_REQUEST			= 602;
const UIEVENT   EVENT_PARTY_BANISH			= 603;
const UIEVENT   EVENT_PARTY_OUT				= 605;
const UIEVENT   EVENT_PARTY_BOARD			= 606;
const UIEVENT	EVENT_PARTY_BOARDREGIST		= 607;
const UIEVENT	EVENT_PARTY_INVIT			= 608;

const UIEVENT   EVENT_PARTY_HEAL			= 611;
const UIEVENT	EVENT_CREATECHAR			= 612;

const UIEVENT	EVENT_OPTION_BGMONOFF		= 700;
const UIEVENT	EVENT_OPTION_EFFONOFF		= 701;
const UIEVENT	EVENT_OPTION_51CHONOFF		= 702;
const UIEVENT	EVENT_OPTION_SOUND			= 703;
const UIEVENT	EVENT_SOUND_VOLUME			= 704;
const UIEVENT	EVENT_DIE					= 705;
const UIEVENT	EVENT_TIMER					= 706;

const UIEVENT	EVENT_CAMERA				= 750;

const UIEVENT	EVENT_FRIEND_REGIST			= 800;
const UIEVENT	EVENT_FRIEND_LIST			= 801;
const UIEVENT	EVENT_FRIEND_DELETE			= 802;
const UIEVENT	EVENT_FRIEND_CUTOFF			= 803;

const UIEVENT	EVENT_CHATT_CUTOFF			= 810;
const UIEVENT	EVENT_WHISPER_CUTOFF		= 811;
const UIEVENT	EVENT_DEAL_CUTOFF			= 812;
const UIEVENT	EVENT_PARTY_CUTOFF			= 813;

const UIEVENT	EVENT_INFO_CUTOFF			= 820;
const UIEVENT	EVENT_INFO_POSITION			= 821;

const UIEVENT	EVENT_ACT_BOW				= 830;
const UIEVENT	EVENT_ACT_SALUTE			= 831;
const UIEVENT	EVENT_ACT_HANDCLAP			= 832;
const UIEVENT	EVENT_ACT_DEATH				= 833;
const UIEVENT	EVENT_ACT_DANCE				= 834;

const UIEVENT	EVENT_SKILL_SPECIAL			= 900;
const UIEVENT	EVENT_ENCHANTCARD_END		= 901;

const UIEVENT	EVENT_GUILD_TAKEMEMBER		= 950;
const UIEVENT	EVENT_GUILD_REMOVEMEMBER	= 951;
const UIEVENT	EVENT_GUILD_OUT				= 952;
const UIEVENT	EVENT_GUILD_ENCAMP			= 953;
const UIEVENT	EVENT_GUILD_NOTICE			= 954;
const UIEVENT	EVENT_GUILD_ONLINEMEMBERLIST= 955;
const UIEVENT	EVENT_GUILD_ALLMEMBERLIST	= 956;
const UIEVENT	EVENT_GUILD_CAPTAINLEAVE	= 957;
const UIEVENT	EVENT_GUILD_PROMOTE			= 958;
const UIEVENT	EVENT_GUILD_DEMOTE			= 959;
const UIEVENT	EVENT_GUILD_SUBCAPTAINLEAVE	= 960;
const UIEVENT	EVENT_GUILD_CLEANUP			= 961;
const UIEVENT	EVENT_GUILD_AID				= 962;
const UIEVENT	EVENT_GUILD_CREATE			= 963;
const UIEVENT	EVENT_GUILD_RELEASE			= 964;

const UIEVENT	EVENT_PKMODE				= 965;

const UIEVENT	EVENT_PET_ONOFF				= 970;
const UIEVENT	EVENT_PET_CHANGENAME		= 971;

const UIEVENT	EVENT_MYSHOP_OPEN			= 980;
const UIEVENT	EVENT_MYSHOP_CHANGETITLE	= 981;
const UIEVENT	EVENT_MYSHOP_ADDITEM		= 982;
const UIEVENT	EVENT_MYSHOP_REMOVEITEM		= 983;
const UIEVENT	EVENT_MYSHOP_SELLBEGIN		= 984;
const UIEVENT	EVENT_MYSHOP_SELLFINISH		= 985;
const UIEVENT	EVENT_MYSHOP_GETITEMLIST	= 986;
const UIEVENT	EVENT_MYSHOP_BUYITEM		= 987;

const UIEVENT	EVENT_GUILD_WARINFO			= 988;
const UIEVENT	EVENT_GUILD_GETCASTLELIST	= 989;

const UIEVENT	EVENT_TEX_GET				= 990;
const UIEVENT	EVENT_TEX_CHANGE			= 991;

#endif // #ifndef __Wind3D_UInterface_EventCode_Header__
